### ISSUE TITLE
[Kotlin/Wasm]After adding the dependency, the canvas cannot be filled

### ISSUE THREAD

**Issue by Zhou-Kt** [jordond/MaterialKolor#126]
I added it to my Kotlin/Wasm project and didn't do anything, but my layout started to shift to the top left. It was back to normal when I removed the dependency. It has been reproduced many times.

`implementation("com.materialkolor:material-kolor:1.4.4")`

<img width="897" alt="Snipaste_2024-03-26_18-09-11" src="https://github.com/jordond/MaterialKolor/assets/102935354/09f96e2f-e157-4f0a-8755-333236b89849">
<img width="897" alt="Snipaste_2024-03-26_18-09-20" src="https://github.com/jordond/MaterialKolor/assets/102935354/c45b5abf-fbe7-431d-a2ee-5f482bbc7dde">

**Comment by Zhou-Kt** [comment]
v1.4.3 doesn't have such a problem

**Comment by jordond** [comment]
Hrmm, the only change between 1.4.3 and 1.4.4 was updating Kotlin to 1.9.23 and Compose Multiplatform to 1.6.1, it's possible it could be a Compose problem.

**Comment by Zhou-Kt** [comment]
> Hrmm, the only change between 1.4.3 and 1.4.4 was updating Kotlin to 1.9.23 and Compose Multiplatform to 1.6.1, it's possible it could be a Compose problem.

Okay, thanks, there's always some weird problem with kmp.
