### ISSUE TITLE
Android release variant of the library is empty

### ISSUE THREAD

**Issue by fbarthelery** [jordond/MaterialKolor#16]
The Android release variant of the library is empty. The aar contains no .class files.
My guess is it is because of [`isMinifyEnabled = true`](https://github.com/jordond/MaterialKolor/blob/287cedaf6097c5ad280abd40676880382d81edee/material-kolor/build.gradle.kts#L72) in build.gradle.kts.
It should be set to false for an Android library so that the final application can run the minification.

Same for material-color-utilities, [here](https://github.com/jordond/MaterialKolor/blob/287cedaf6097c5ad280abd40676880382d81edee/material-color-utilities/build.gradle.kts#L62C25-L62C25)

**Comment by jordond** [comment]
I've kicked off a new release 1.2.2, once its published, give it a shot and see if it fixes it 👍

**Comment by jordond** [comment]
Fixed in 1.2.2

**Comment by fbarthelery** [comment]
Much better! Thanks
