### ISSUE TITLE
Export Theme.kt from the sample app

### ISSUE THREAD

**Issue by Nek-12** [jordond/MaterialKolor#185]
It would be great to be able to visit the sample app and export the theme as a kotlin file to statically embed it in the app, just like with the (abandoned and buggy) https://github.com/material-foundation/material-theme-builder. In that case, the library would serve  as a modern, working replacement for those who just want to build a static theme and serve a double purpose.

**Comment by jordond** [comment]
duplicate of #73

**Comment by jordond** [comment]
I have just released the first version of [MaterialKolor Builder](https://github.com/jordond/materialkolorbuilder)! Check it out at [materialkolor.com](https://materialkolor.com).
