### ISSUE TITLE
Plug in custom color hex in the demo app 

### ISSUE THREAD

**Issue by Nek-12** [jordond/MaterialKolor#187]
https://demo.materialkolor.com/ allows only a predefined selection of colors. I'd like to enter my own hex color

**Comment by jordond** [comment]
duplicate of #73

**Comment by jordond** [comment]
I have just released the first version of [MaterialKolor Builder](https://github.com/jordond/materialkolorbuilder)! Check it out at [materialkolor.com](https://materialkolor.com).
