### ISSUE TITLE
[Question] Android 12+ dynamic theme support?

### ISSUE THREAD

**Issue by BobbyESP** [jordond/MaterialKolor#192]
Hi! I'm adding this AMAZING library to a new app I'm doing (and maybe porting others to it) but I've seen that it currently doesn't support the automatic Android 12 and higher versions coloring. Is it something that I'm missing or it's intended not to be on the library?

Thanks!

**Comment by jordond** [comment]
`dynamicDarkColorScheme()` and `dynamicLightColorScheme()` generate their own `ColorScheme` so it would negate the generated ColorScheme from this library. That and it is Android only.

**Comment by BobbyESP** [comment]
> `dynamicDarkColorScheme()` and `dynamicLightColorScheme()` generate their own `ColorScheme` so it would negate the generated ColorScheme from this library. That and it is Android only.

Okayy! Thank you so much for the fast response and the clarity. Have a nice day
