### ISSUE TITLE
The tone of the `onXXXContainer` in the light theme is incorrect

### ISSUE THREAD

**Issue by KawabeAtsushi** [jordond/MaterialKolor#224]
The tone of the `onXXXContainer` in the light theme is incorrect.

For example, `onPrimaryContainer` is defined as follows:

```kotlin
public fun onPrimaryContainer(): DynamicColor = DynamicColor(
    :
    tone = { scheme ->
        when {
            isFidelity(scheme) -> {
                DynamicColor.foregroundTone(primaryContainer().tone(scheme), 4.5)
            }
            isMonochrome(scheme) -> if (scheme.isDark) 0.0 else 100.0
            else -> if (scheme.isDark) 90.0 else 30.0 // <- here
        }
    },
    :
```

The value should be 10.0 instead of 30.0.

I found that `onPrimaryContainer`, `onSecondaryContainer`, and `onTertiaryContainer` have incorrect values.

Additionally, your [MaterialKolor Builder](https://materialkolor.com/) shows incorrect tone values for the dark theme compared to the original [Material Theme Builder](https://material-foundation.github.io/material-theme-builder).

Original:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/8114915d-d1f0-46ae-8df9-409b3fba71b3">

Yours:
<img width="468" alt="image" src="https://github.com/user-attachments/assets/f31c2ca1-9548-4a6a-85cf-cef32e91ffb4">

Thank you for providing a great library.

**Comment by kirill-grouchnikov** [comment]
These are correct values. See the "Color Token Alignment" section in https://m3.material.io/blog/material-3-compose-1-3

**Comment by kirill-grouchnikov** [comment]
You can also see the latest M3 spec for color tokens at https://m3.material.io/styles/color/static/baseline by expanding each section (Primary colors, Secondary colors, etc) and clicking on "On primary container", "On secondary container", etc.

**Comment by KawabeAtsushi** [comment]
Oh, sorry, I wasn't aware of the new information.
Thank you for the information.
Can I close this issue?

**Comment by jordond** [comment]
Unfortunately Google hasn't updated their Material theme builder in awhile, so their values are out of date 😞.

Also for future reference, the values are all ported from the [mcu](https://github.com/material-foundation/material-color-utilities/blob/main/java/dynamiccolor/MaterialDynamicColors.java) library.

There is even a [Github Actions workflow](https://github.com/jordond/MaterialKolor/actions/workflows/upstream.yml) that checks the upstream library for any changes related to the java code, and opens an issue on this repo.
