### ISSUE TITLE
Unable to build ios app

### ISSUE THREAD

**Issue by TheReprator** [jordond/MaterialKolor#47]
getting error:
'pod install' command failed with code 1.
Error message:
Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:
    project 'path/to/Project.xcodeproj'
        Please, check that podfile contains following lines in header:
        source 'https://cdn.cocoapods.org'

        Please, check that each target depended on ComposeApp contains following dependencies:

**Comment by jordond** [comment]
Can you check out #48 and see if it fixes it for you?
