### ISSUE TITLE
Add Wasm support 

### ISSUE THREAD

**Issue by andres04** [jordond/MaterialKolor#70]
Since https://kmp.jetbrains.com/ supports Web Assembly now, It would be great to have Wasm support.

**Comment by terrakok** [comment]
Waiting the new version to add a wasm target: https://terrakok.github.io/compose-material-3-gallery/ 😉

**Comment by jordond** [comment]
@terrakok I haven't released it yet because the `wasmJs` target requires Compose Multiplatform 1.6.0, and it's currently in alpha. I have made a 1.4.0-alpha01 pre-release in the meantime.
