### ISSUE TITLE
Add a code snippet to the demo web app

### ISSUE THREAD

**Issue by terrakok** [jordond/MaterialKolor#73]
It would be awesome to have a code snippet ready to copy-paste with material theme colors in the demo web app.
1) select a seed color and a palette style
2) paste ready to use code in your app if you don't need dynamic theme switcher

**Comment by jordond** [comment]
Oh for sure. The web version of the demo was only published because it was "free". I've been wanting to write a completely different demo for just the web that is designed better and has a feature like you mentioned. Just haven't found the time 😅

**Comment by jordond** [comment]
I have just released the first version of [MaterialKolor Builder](https://github.com/jordond/materialkolorbuilder)! Check it out at [materialkolor.com](https://materialkolor.com).

**Comment by terrakok** [comment]
Added a theme from KolorBuilder to my wizard: https://terrakok.github.io/Compose-Multiplatform-Wizard/ (and mentioned it as well 👍 )
